name: Build JS SDK
on:
  push:
    branches:
      - main
      - dev
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set the release version (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: set the release version (nightly)
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: echo "RELEASE_VERSION=nightly" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup target add wasm32-wasi
      - name: Install wasm-opt
        run: |
          sudo apt install -y binaryen xz-utils
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Build
        run: |
          bash ./install-deps.sh
          env
          (cd js-vendor && npm install)
          make release
          cp js-engine.wasm js-engine-${{ env.RELEASE_VERSION }}.wasm
      - name: Js files Test
        run: |
          cargo build -p test-runner --release
          bash ./tests/test-js-files.sh 
          ./target/release/test-runner up &
          sleep 5
          cargo test -p test-runner --release
      - name: Upload CLI
        uses: actions/upload-artifact@v2
        with:
          name: js-engine.wasm
          path: js-engine-${{ env.RELEASE_VERSION }}.wasm
      - name: upload webassembly to Github release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: js-engine-${{ env.RELEASE_VERSION }}.wasm
          tag: ${{ github.ref }}

  release-nightly:
    name: update nightly release
    runs-on: ubuntu-latest
    needs: 
      - build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v3
        with:
          name: js-engine.wasm

      - name: Delete nightly tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          delete_release: true

      - name: Recreate nightly tag and release
        uses: rajatjindal/release-action@v0.0.1
        with:
          tag: nightly
          allowUpdates: true
          prerelease: true
          artifacts: "js-engine-*"
          commit: ${{ github.sha }}
          body: |
            This is a "nightly" release webassembly of runtime-land-js-sdk. It is automatically built from the latest commit on the main branch. It includes some new features and bug fixes that have not yet been released. Be careful when using this version with land-cli as it may be unstable or incompatible.